- name: Validate sshd service and external connectivity
  hosts: restore
  become: yes

  tasks:
    - name: Ensure sshd is running and enabled
      service:
        name: sshd
        state: started
        enabled: yes

    - name: Ping external server to verify network connectivity
      shell: ping -c 3 8.8.8.8
      register: ping_result
      failed_when: "'0% packet loss' not in ping_result.stdout"

    - name: Show ping result if successful
      debug:
        msg: "Ping successful with output:\n{{ ping_result.stdout }}"
      when: "'0% packet loss' in ping_result.stdout"
