- name: Transfer 2 latest backup files to restore node
  hosts: backup
  become: yes
  vars:
    restore_ip: 192.168.51.21
    restore_user: babonza  # ganti sesuai user restore
  tasks:
    - name: Find latest etc backup file
      shell: ls -1t /var/backups/etc-*.tar.gz | head -n1
      register: latest_etc_backup
      changed_when: false

    - name: Find latest crontab backup file
      shell: ls -1t /var/backups/crontab-*.txt | head -n1
      register: latest_crontab_backup
      changed_when: false
      ignore_errors: yes

    - name: Ensure destination directory exists on restore
      ansible.builtin.shell: "mkdir -p /backup && chmod 755 /backup"
      delegate_to: "{{ restore_ip }}"
      become: yes

    - name: Transfer etc backup to restore node
      synchronize:
        src: "{{ latest_etc_backup.stdout }}"
        dest: "/backup/"
        mode: push
        rsync_opts:
          - "--rsync-path='sudo rsync'"
      delegate_to: localhost  # synchronize runs locally, but connects from source to dest

    - name: Transfer crontab backup to restore node
      synchronize:
        src: "{{ latest_crontab_backup.stdout }}"
        dest: "/backup/"
        mode: push
        rsync_opts:
          - "--rsync-path='sudo rsync'"
      when: latest_crontab_backup.stdout is defined
      delegate_to: localhost
