---
- name: Synchronize /var/backup to VM Restore:/restore
  hosts: vm_backup
  gather_facts: no
  tasks:
    - name: Sync backup files to VM Restore
      ansible.posix.synchronize:
        src: /var/backup/
        dest: /restore/
        mode: push
        dest_host: 192.168.1.20
      delegate_to: localhost
