---
- name: Direct transfer from VM Backup to VM Restore
  hosts: backup
  gather_facts: no
  tasks:
    - name: Synchronize /var/backup to VM Restore:/restore
      ansible.posix.synchronize:
        src: /var/backup/
        dest: /restore/
        mode: push
      delegate_to: localhost
      vars:
        ansible_ssh_user: babonza
        ansible_ssh_pass: P@ssw0rd
        ansible_host: 192.168.51.21
        rsync_path: "sudo rsync"
