---
- name: Transfer file backup dari VM 1 ke VM 2
  hosts: backup
  become: true
  gather_facts: no

  #vars:
  #  source_dir: /var/backups/
  #  dest_user: babonza
  #  dest_host: 192.168.51.21
  #  dest_path: restore/

  tasks:
    - name: Jalankan rsync dari VM 1 ke VM 2
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" /var/backups/ babonza@192.168.51.21:restore/

    - name: Tampilkan hasil rsync
      ansible.builtin.debug:
        var: rsync_result.stdout_lines
