- name: Sync backup files to VM Restore
  hosts: backup
  become: true
  tasks:
    - name: Rsync to VM Restore
      ansible.posix.synchronize:
        src: /var/backups/
        dest: babonza@192.168.30.18:restore/
        mode: push
        rsync_opts:
          - "--rsh=ssh -o StrictHostKeyChecking=no"
