---
- name: Transfer file backup dari VM 1 ke VM 2
  hosts: backup
  gather_facts: no

  vars:
    source_dir: /var/backups/
    dest_user: babonza
    dest_host: 192.168.51.21
    dest_path: /home/babonza/restore/

  tasks:
    - name: Jalankan rsync dari VM 1 ke VM 2
      ansible.builtin.shell: |
        rsync -avz {{ source_dir }} {{ dest_user }}@{{ dest_host }}:{{ dest_path }}
      register: rsync_result

    - name: Tampilkan hasil rsync
      ansible.builtin.debug:
        var: rsync_result.stdout_lines
