---
- name: Transfer file backup dari VM 1 ke VM 2
  hosts: 192.168.30.17
  become: true
  gather_facts: no

  #vars:
  #  source_dir: /var/backups/
  #  dest_user: babonza
  #  dest_host: 192.168.51.21
  #  dest_path: restore/

  tasks:
    - name: Jalankan rsync dari VM 1 ke VM 2
      command: >
        scp /var/backups/ admin@192.168.51.47:/home/admin/

