---
- name: Restore configs on DR servers
  hosts: all
  become: yes
  tasks:
    - name: Extract /etc backup
      unarchive:
        src: "/mnt/backups/etc-{{ inventory_hostname }}.tar.gz"
        dest: /
        remote_src: yes

    - name: Restore crontab
      cron:
        name: "Recovered crontab"
        job: "{{ lookup('file', '/mnt/backups/crontab-' + inventory_hostname + '.txt') }}"
